# Generated by Django 5.2.1 on 2025-05-15 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('health', 'Healthcare'), ('fintech', 'FinTech'), ('edtech', 'EdTech'), ('ecommerce', 'E-commerce'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scaling', 'Scaling')], max_length=20)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('interests', models.JSONField(default=list)),
                ('looking_for', models.TextField(help_text='What kind of connections are you looking for?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
