# Generated by Django 5.2.1 on 2025-05-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founderprofile',
            name='interests',
            field=models.JSONField(default=list, help_text='Select your interests and expertise areas'),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='looking_for',
            field=models.JSONField(default=list, help_text='What kind of connections are you looking for?'),
        ),
    ]
