# Generated by Django 5.2.1 on 2025-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_founderprofile_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='accelerator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='biggest_challenge',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='business_model',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2b2c', 'B2B2C'), ('c2c', 'C2C'), ('d2c', 'D2C'), ('other', 'Other')], default='b2b', max_length=20),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='capital_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='city_region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='company_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of employees'),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='digital_nomad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='funding_stage',
            field=models.CharField(choices=[('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D+')], default='pre_seed', max_length=20),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='goals_next_6_months',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='has_exited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='is_bootstrapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='is_vc_backed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='languages_spoken',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='preferred_call_availability',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='preferred_call_duration',
            field=models.PositiveIntegerField(default=30, help_text='Preferred call duration in minutes'),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='revenue_stage',
            field=models.CharField(choices=[('pre_revenue', 'Pre-revenue'), ('1k_10k', '$1K-$10K MRR'), ('10k_50k', '$10K-$50K MRR'), ('50k_100k', '$50K-$100K MRR'), ('100k_plus', '$100K+ MRR'), ('profitable', 'Profitable')], default='pre_revenue', max_length=20),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('cto', 'CTO'), ('cmo', 'CMO'), ('ceo', 'CEO'), ('coo', 'COO'), ('other', 'Other')], default='founder', max_length=20),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='spiritual_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('early_traction', 'Early Traction'), ('growth', 'Growth'), ('scaling', 'Scaling'), ('mature', 'Mature')], default='idea', max_length=20),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='startup_values',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='target_market',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='tech_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='underrepresented_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
