# Generated by Django 5.2.1 on 2025-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founderprofile',
            name='biggest_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='business_model',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2b2c', 'B2B2C'), ('c2c', 'C2C'), ('d2c', 'D2C'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='city_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='funding_stage',
            field=models.CharField(blank=True, choices=[('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='goals_next_6_months',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('health', 'Healthcare'), ('fintech', 'FinTech'), ('edtech', 'EdTech'), ('ecommerce', 'E-commerce'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='interests',
            field=models.JSONField(help_text='Select your interests and expertise areas'),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='looking_for',
            field=models.JSONField(help_text='What kind of connections are you looking for?'),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='preferred_call_availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='revenue_stage',
            field=models.CharField(blank=True, choices=[('pre_revenue', 'Pre-revenue'), ('1k_10k', '$1K-$10K MRR'), ('10k_50k', '$10K-$50K MRR'), ('50k_100k', '$50K-$100K MRR'), ('100k_plus', '$100K+ MRR'), ('profitable', 'Profitable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('cto', 'CTO'), ('cmo', 'CMO'), ('ceo', 'CEO'), ('coo', 'COO'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scaling', 'Scaling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='startup_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('early_traction', 'Early Traction'), ('growth', 'Growth'), ('scaling', 'Scaling'), ('mature', 'Mature')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='startup_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='target_market',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
