# Generated by Django 5.2.1 on 2025-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_founderprofile_biggest_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderprofile',
            name='biggest_challenge',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='goals_next_6_months',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='preferred_call_availability',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='jobs',
            field=models.JSONField(default=list, help_text='Select your job roles'),
        ),
    ]
