# Generated by Django 5.2.1 on 2025-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_founderprofile_biggest_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderprofile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='biggest_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='goals_next_6_months',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='preferred_call_availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
