# Generated by Django 5.2.1 on 2025-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_founderprofile_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='job_title',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('cto', 'CTO'), ('cmo', 'CMO'), ('ceo', 'CEO'), ('coo', 'COO'), ('product_manager', 'Product Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('other', 'Other')], max_length=50),
        ),
    ]
