# Generated by Django 5.2.1 on 2025-05-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_founderprofile_role_founderprofile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderprofile',
            name='digital_nomad',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='preferred_call_availability',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='preferred_call_duration',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='spiritual_interests',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='startup_stage',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='startup_values',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='target_market',
        ),
        migrations.RemoveField(
            model_name='founderprofile',
            name='underrepresented_founder',
        ),
    ]
