# Generated by Django 5.2.1 on 2025-05-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_founderprofile_digital_nomad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderprofile',
            name='description',
        ),
    ]
